### ISSUE TITLE
Metadata doesn't seem to manifest themselves in output files

### ISSUE THREAD

**Issue by ribose-jeffreylau** [metanorma/metanorma-docker#1]
Running metanorma-docker would seem to make metadata disappear in the produced files.

## Steps to reproduce

From Windows, PuTTY into a macOS terminal session, then clone https://github.com/calconnect/vcard and then `cd` into `csd/datetime-explicit/`.  Then run:

```console
> docker run -v "$(pwd)":/metanorma/ ribose/metanorma -t csd -x xml,doc,html,pdf csd-datetime-explicit.adoc
```

## Results

The produced files do not contain things like document title, the document number gets replaced by "99999", etc.

## Expected output

The produced files contain metadata from the headers of the file `csd-datetime-explicit.adoc`.

**Comment by ronaldtse** [comment]
Thanks for the report. I feel that the Putty terminal is doing something funny with “pwd” for volume sharing?

Could you run the docker container (in the Mac via the session) with bash, enter it, and run Metanorma inside the container against the same files?

**Comment by ronaldtse** [comment]
I don't think this is happening anymore, closing it. Feel free to reopen later.
