### ISSUE TITLE
metanorma/mn container contains broken lutaml 0.7.3

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#100]
LutaML 0.7.3 gem is broken that it cannot be run without byebug. 

The working release is 0.7.4 which is released today. 

We need to rebuild the containers. 

Reported by @ribose-jeffreylau

**Comment by CAMOBAP** [comment]
The rebuild will be triggered once https://github.com/metanorma/metanorma-docker/pull/101 merged

**Comment by CAMOBAP** [comment]
Done https://github.com/metanorma/metanorma-docker/runs/3006984970?check_suite_focus=true#step:4:5760

@ronaldtse @ribose-jeffreylau which workflow can I restart to make sure that it works as expected?

**Comment by ribose-jeffreylau** [comment]
@CAMOBAP Try this: https://github.com/CalConnect/csd-transcription-systems/actions/runs/1006681162

**Comment by ribose-jeffreylau** [comment]
It seems to be fixed.  Thanks @CAMOBAP !
