### ISSUE TITLE
Tag functionality doesn't work anymore

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-docker#115]
https://github.com/metanorma/metanorma-docker/runs/3448129073?check_suite_focus=true#step:7:17

cc @ronaldtse

**Comment by CAMOBAP** [comment]
Looks like it happens after https://github.com/metanorma/metanorma-docker/commit/b584782d75278ed412c62565c11f0f07df03f149

To be continued...

**Comment by ronaldtse** [comment]
The Makefile has to be updated, but I think the right solution is to revert the removal of squash. The docker build squash option flattens the image completely, but we don’t really want that. Let me do the revert there.

**Comment by CAMOBAP** [comment]
> but I think the right solution is to revert the removal of squash

ok

I think the issue why it fails because we don't do `tag` before `push`

@ronaldtse will it be ok, if I will push this tiny fix to make CI green?

**Comment by ronaldtse** [comment]
Of course! Please proceed.

**Comment by CAMOBAP** [comment]
Fixed, rest will be addressed with #113
