### ISSUE TITLE
(URGENT) Provide instructions for compiling documents on MS Windows

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-docker#122]
Currently we use this command to compile on Linux and MacOS machines.

`docker run -v "$(pwd)":/metanorma -v ${HOME}/.fontist/fonts/:/config/fonts  metanorma/mn  metanorma compile --agree-to-terms -t ogc -x xml,html,doc document.adoc`

The command above does not work on MS Windows. 

Cc: @sergioTaleisnik

**Comment by ronaldtse** [comment]
@CAMOBAP can you please help check? Thanks

**Comment by ronaldtse** [comment]
@ghobona @sergioTaleisnik have you tried the Docker-Windows instruction here?

https://www.metanorma.org/install/docker/
<img width="763" alt="Screenshot 2021-11-20 at 5 53 10 PM" src="https://user-images.githubusercontent.com/11865/142722025-210f0a51-bcbe-48a6-91cf-2bcfdfcfa90e.png">

```sh
docker run -v "%cd%":/metanorma/ -w /metanorma metanorma/metanorma metanorma compile -t {flavor} -x {output-formats} {my-document-path}
```

**Comment by ronaldtse** [comment]
Actually the command on this page works better:

https://www.metanorma.org/author/topics/building/font-management/

<img width="797" alt="Screenshot 2021-11-20 at 5 54 13 PM" src="https://user-images.githubusercontent.com/11865/142722069-abf6dd81-cf9b-4d04-b13e-609d18f0d2af.png">

**Comment by ghobona** [comment]
Thanks @ronaldtse .

@sergioTaleisnik Please try out the command and let us know if it worked on your machine.

**Comment by CAMOBAP** [comment]
I hope the issue was resolved, if not, please reopen
