### ISSUE TITLE
Build Linux/arm64 version of containers

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#123]
Using docker's buildx:
* GitHub Action: https://github.com/docker/setup-buildx-action
* https://carlosedp.medium.com/cross-building-arm64-images-on-docker-desktop-254d1e0bc1f9
* https://community.arm.com/arm-community-blogs/b/tools-software-ides-blog/posts/getting-started-with-docker-on-arm

**Comment by CAMOBAP** [comment]
Done some time ago https://github.com/metanorma/metanorma-docker/actions/runs/2309875747
