### ISSUE TITLE
Docker failing to run

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-docker#127]
Possibly failing to clone git://github.com/brucemiller/LaTeXML.git

https://github.com/metanorma/metanorma-docker/runs/4773975440?check_suite_focus=true

**Comment by ronaldtse** [comment]
This is because of
https://github.com/metanorma/metanorma-docker/blob/e52afebf465636fc810263da02c4e3f2edf34070/ubuntu.sh#L14

This brucemiller/LaTeXML@9a0e7dc5 commit is no longer around.

**Comment by ronaldtse** [comment]
@CAMOBAP but do we still need to include LaTeXML? If not we should remove that?

**Comment by CAMOBAP** [comment]
> This is because of
> 
> https://github.com/metanorma/metanorma-docker/blob/e52afebf465636fc810263da02c4e3f2edf34070/ubuntu.sh#L14
> 
> This [brucemiller/LaTeXML@9a0e7dc](https://github.com/brucemiller/LaTeXML/commit/9a0e7dc5) commit is no longer around.

strange because it is available `https://github.com/brucemiller/LaTeXML/commit/9a0e7dc5`

**Comment by CAMOBAP** [comment]
> @CAMOBAP but do we still need to include LaTeXML? If not we should remove that?

good question, recently we discussed https://github.com/metanorma/metanorma-cli#external-dependencies and we don't depend on it

fix in the progress

**Comment by CAMOBAP** [comment]
@opoudjis @ronaldtse 

Fixed, should I retag `v1.5.6pre`?

**Comment by ronaldtse** [comment]
Yes please, thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse probably it's not make sense because v1.5.6 passed successfully
