### ISSUE TITLE
Automatically push/deploy Travis built container to Docker Hub

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#13]
@CAMOBAP795 just like https://github.com/riboseinc/jenkins-docker/blob/master/.travis.yml

Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse Done https://github.com/metanorma/metanorma-docker/commit/39cdac8d04b6a0f62edbfabbe51ba7089954b92b

**Comment by ronaldtse** [comment]
@CAMOBAP795 it's not pushing to Docker Hub yet:

```
Skipping a deployment with the script provider because this is not a tagged commit
```

Can you help update the documentation on how to make a tagged commit for building the container?

**Comment by ronaldtse** [comment]
I'm not even sure if we want a tagged commit because the version of the container will purely depend on the version of Metanorma. We just want to get the containers built and deployed.

**Comment by CAMOBAP795** [comment]
For now push happens only when you add tag to git repo like this
`git tag vSome.Version`
`git push origin master --tags`

If we need push on each commit to master it can be easily implemented by removing `tags` property

@ronaldtse just let me know

**Comment by ronaldtse** [comment]
@CAMOBAP795 I guess it's a good idea to restrict to tags, but we want to make sure to remember this requirement. Can you update the README (and in jenkins-docker) so we remember to do it? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse done https://github.com/metanorma/metanorma-docker/pull/15 if it's ok I will do the same for `jenkins-docker`

**Comment by ronaldtse** [comment]
@CAMOBAP795 yes, please do the same for jenkins-docker. Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse sure, just updated https://github.com/metanorma/metanorma-docker/pull/15, is it ok now?
