### ISSUE TITLE
Push to GitHub Container Registry in addition to Docker Hub

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#134]

**Comment by CAMOBAP** [comment]
At the moment technically there is no issue to migrate docker/build-and-push action (which is used already in https://github.com/metanorma/metanorma-docker-private/)

I think for troubleshooting it will be nice to have Makefile also, but also will be nice to not maintain both Makefile and docker.yml separately

I just wondering is it possible to keep labels/tags in some config to simplify Makefile

@ronaldtse may be you know some tool which can help with this, or can suggest some docker expect in our team?

**Comment by ronaldtse** [comment]
> I think for troubleshooting it will be nice to have Makefile also, but also will be nice to not maintain both Makefile and docker.yml separately

I agree that the Makefile is too complex -- I wrote the original version and @ribose-jeffreylau improved on it.

I suggest we just get rid of the Makefile for now, and re-build a Makefile after we have a good docker.yml.

**Comment by ronaldtse** [comment]
In addition, the jobs like #133 take a long time to validate. We should probably use a GHA matrix to expand on the flavors to test the docker container, i.e. build it, and then run the tests of multiple flavors on the built container.

**Comment by CAMOBAP** [comment]
Waiting for CI

**Comment by ronaldtse** [comment]
In the latest build (https://github.com/metanorma/metanorma-docker/actions/runs/1995185481), it's still only pushing to docker.io not gchr.io. Notice that on the front page of this repo there is still no listed package:
<img width="212" alt="Screenshot 2022-03-17 at 9 15 46 AM" src="https://user-images.githubusercontent.com/11865/158717339-d32278f5-4571-4f6a-9114-8f44daba9de1.png">

In order to also push to gchr.io, we also need to tag the containers with a gchr.io ID. I don't think we're doing that now?

**Comment by CAMOBAP** [comment]
@ronaldtse last push was successful, but I cannot see containers probably because of visibility settings. May I ask you to have a look?

**Comment by ronaldtse** [comment]
Yes it worked, and permissions now fixed. Thanks @CAMOBAP !

<img width="464" alt="Screenshot 2022-03-18 at 10 56 11 AM" src="https://user-images.githubusercontent.com/11865/158928852-0efca692-9226-4398-ba11-eb8b3b9fb477.png">
