### ISSUE TITLE
Not pushing to metanorma/metanorma

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#14]
@CAMOBAP795 can you please help ensure that it's pushing to metanorma/metanorma (https://cloud.docker.com/u/metanorma/repository/docker/metanorma/metanorma/general).

Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse yep https://cloud.docker.com/u/metanorma/repository/docker/metanorma/metanorma looks empty i will check what is happens

**Comment by CAMOBAP795** [comment]
@ronaldtse push functionality works, but I think we need to change version strategy from `yyyyMMdd.branch` to version of `metanorma-cli`

How do you think?

**Comment by ronaldtse** [comment]
Yes, I agree. Could you please help update it? Thanks.

**Comment by CAMOBAP795** [comment]
There is still some problems with push from travis (local push works correct)

@ronaldtse could you please clarify do we have an special user for push in travis or you just added there your credentials?

**Comment by ronaldtse** [comment]
@CAMOBAP795 but that is strange -- Docker Hub says it has been pushed? I didn't push them so it must have been the Travis job?

<img width="378" alt="image" src="https://user-images.githubusercontent.com/11865/55668601-c2ee8780-589e-11e9-84e0-df53508ca8cc.png">

**Comment by ronaldtse** [comment]
When you correlate the build history, both were pushed by your commits:

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/11865/55668618-f7fada00-589e-11e9-9d67-40dc88fc8d10.png">

**Comment by ronaldtse** [comment]
And it looks like Travis is pushing (deploying) on both builds. A commit should only be built once?

Previously, `mn` was the "edge version", and `metanorma` is the development version. For example, sometimes we can't wait until all the gems are released to build the container, so we have to use `mn`. 

Perhaps we can either use the YYYYMMDD for edge builds under `metanorma` or `mn`?

**Comment by CAMOBAP795** [comment]
@ronaldtse 

> but that is strange -- Docker Hub says it has been pushed? I didn't push them so it must have been the Travis job?

those ones which on hub.docker.io was pushed manually from my machine (during investigation)

> When you correlate the build history, both were pushed by your commits:

As you may see from travis history  https://travis-ci.com/metanorma/metanorma-docker/builds all attempts to `docker push` failed because `denied: requested access to the resource is denied`

> And it looks like Travis is pushing (deploying) on both builds. A commit should only be built once?

It do deployment only on tagged commits

> Perhaps we can either use the YYYYMMDD for edge builds under metanorma or mn?

Yes sure

**Comment by ronaldtse** [comment]
@CAMOBAP795 yes you're right. I forgot to give push permissions to the CI user. I've restarted the build and see if it works.

**Comment by CAMOBAP795** [comment]
It works now, could you please double check the same for https://travis-ci.com/riboseinc/jenkins-docker
