### ISSUE TITLE
Use multi-stage Dockerfile for all containers (to replace squash)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#147]
According to BuildKit:
> experimental flag squash is removed with BuildKit. You should squash inside build using a multi-stage Dockerfile for efficiency
https://github.com/docker/buildx/blob/1ca30a58c2f25a7f72a2fdb5d62e82bf1e2fa37c/commands/build.go#L411

**Comment by ronaldtse** [comment]
The latest containers in #145 are 2.12 GB each, which is a bit excessive.

**Comment by CAMOBAP** [comment]
Done
