### ISSUE TITLE
(URGENT) Build failed on release of 1.5.21

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#158]
https://github.com/metanorma/metanorma-docker/actions/runs/2819352810

This failure is blocking usage of the metanorma container here:
https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/issues/160

Specifically, the "alpine, itu" job failed.

**Comment by CAMOBAP** [comment]
@ronaldtse there are clearly issues with tag updates:
 - latest, was updated 1 month ago https://hub.docker.com/layers/metanorma/metanorma/metanorma/latest/images/sha256-ae6bf7f13858b61afc8dbcc4bb2e33a7dd786d76c28d23b8f9d184627ecf7407?context=explore
 - main, was updated 2 months ago

Researching in deep how https://github.com/metanorma/metanorma-docker/blob/main/.github/workflows/build-push.yml#L383-L406 works

**Comment by ronaldtse** [comment]
It looks like the "push" step now works but the push for alpine failed:

https://github.com/metanorma/metanorma-docker/runs/7821301262?check_suite_focus=true

```
error: failed to solve: failed to push docker.io/metanorma/metanorma:alpine-1.5.21: failed to copy: invalid status response 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. for https://n06iacprodeus1file4.blob.core.windows.net/cc668d58e0214296838da85406341e71/98e937a2311bed11bd6e14cb655affb7?sv=2019-07-07&sr=b&sig=u8T8cdG6l1T8nrYbr%2FuZ5mD%2BcqLwkQ%2BsNP9K19nmGQw%3D&se=2022-08-13T20%3A08%3A30Z&sp=r&rscl=x-e2eid-d5f2e0ee-77f24b03-843c4dd0-fc710282

Error: buildx failed with: error: failed to solve: failed to push docker.io/metanorma/metanorma:alpine-1.5.21: failed to copy: invalid status response 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. for
```

**Comment by ronaldtse** [comment]
`latest` should work:
https://hub.docker.com/r/metanorma/metanorma/tags
<img width="920" alt="Screen Shot 2022-08-14 at 12 10 48 PM" src="https://user-images.githubusercontent.com/11865/184522127-668de766-14b3-453f-ae43-a09d37ad8f4f.png">

**Comment by ronaldtse** [comment]
The rerun of "alpine, itu" passed, but failed at "metanorma alpine push". 

The rerun of "metanorma alpine push" finally worked.

The job is now completed and back to green. Closing for now.
