### ISSUE TITLE
metanorma-alpine stucked on "#15 11180.4 Resolving dependencies........"

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-docker#159]
https://github.com/metanorma/metanorma-docker/actions/runs/2924154629

I have restarted CI several times, no success, still looks like CI issues I will try retag

**Comment by CAMOBAP** [comment]
There is no loop during build on local machine `docker buildx build . -f Dockerfile.alpine --build-arg METANORMA_IMAGE_NAME=metanorma-alpine -o type=docker --tag metanorma/metanorma:local --platform linux/arm64`

Still investigating...

**Comment by CAMOBAP** [comment]
Re-tagged to exclude GHA infrastructure issues https://github.com/metanorma/metanorma-docker/actions/runs/2939331625

**Comment by CAMOBAP** [comment]
Looks like a known issue https://github.com/rubygems/rubygems/issues/5871 temporally downgraded bundler to 2.3.20

**Comment by CAMOBAP** [comment]
Merged

**Comment by Nakilon** [comment]
Have you been debugging it deeper?
It hangs for me on version 2.1.4. It kind of goes insane parsing all the versions of all the gems from the rubygem when I just issue the command `gem install bundler:2.4.22`
