### ISSUE TITLE
(URGENT) Separate Alpine jobs to not block release using Ubuntu

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#162]
The Alpine branch of the docker images are rather unstable, which is currently blocking release on Ubuntu.

The Alpine code is still somewhat experimental given that Ruby/Rubygems only recently addressed the musl issue in binary gems, we should keep this Alpine release workflow separate and not blocking the Ubuntu release.

**Comment by CAMOBAP** [comment]
Done
