### ISSUE TITLE
(URGENT) Broken docker images when running GHA due to pngcheck

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#164]
Example: https://github.com/metanorma/iso-10303-2/actions/runs/3059351763/jobs/4936626413

When the docker image was built, pngcheck 0.2.5 was used but it was not compilable on Linux without the correct tooling. pngcheck 0.2.6 fixed this but this image doesn't include it and does not work.

We need to urgently re-publish the Metanorma Docker image for this particular metanorma-cli version.

**Comment by ronaldtse** [comment]
This is the workaround we had to do for it https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/pull/9

**Comment by CAMOBAP** [comment]
Restarted pipeline for [v1.6.1](https://github.com/metanorma/metanorma-docker/tree/v1.6.1) it should bundle install to include latest pngcheck gem

I will doublecheck in logs

**Comment by CAMOBAP** [comment]
caching temporally disabled to release updated docker images

**Comment by CAMOBAP** [comment]
New docker image released with updated pngcheck.

To resurrect caching, maybe we can do `bundle install` before `docker build` and them `COPY Gemfile.lock` to image so we will be able to reuse previous cached layers and `bundle install` will always be up-to-date

@ronaldtse @abunashir @opoudjis any thoughts on this?

**Comment by ronaldtse** [comment]
@CAMOBAP that's perfect. Thank you!
