### ISSUE TITLE
Docker pull error: Manifest for metanorma/metanorma:latest not found

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-docker#17]
Running this command, as shown on the README.md, ```docker pull metanorma/metanorma```

I got this error:

```Error response from daemon: manifest for metanorma/metanorma:latest not found```

So I then checked the docker hub to get the exact name of the tags https://hub.docker.com/r/metanorma/metanorma/tags

Then I successfully managed to pull the image using this command ```docker pull metanorma/metanorma:1.1.6```

**Comment by ronaldtse** [comment]
Thank you @ghobona , we will amend the flow to also publish a `latest` tag -- that was missing when we changed the namespace from `ribose` to `metanorma` 👍

**Comment by ronaldtse** [comment]
Should be resolved in 51211f7 .

**Comment by CAMOBAP795** [comment]
Fixed
