### ISSUE TITLE
Release manually

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-docker#170]
Source issues: https://github.com/metanorma/metanorma-ogc/issues/473, https://github.com/metanorma/metanorma-ieee/issues/198

Release v1.6.8 failed a week ago (https://github.com/metanorma/metanorma-docker/actions/runs/3621578919) due the error in relaton-ieee:
```
/usr/local/bundle/gems/relaton-ieee-1.14.0/lib/relaton_ieee/ieee_bibliographic_item.rb:70:in `to_hash': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /usr/local/bundle/gems/relaton-bib-1.14.0/lib/relaton_bib/document_relation.rb:75:in `to_hash'
	from /usr/local/bundle/gems/relaton-bib-1.14.0/lib/relaton_bib.rb:88:in `block in single_element_array'
```
It seems this error fixed a few days ago yet (doesn't occur locally).

Also, the error
```
undefined method `name' for nil:NilClass

        while n.name == "p" && n["type"] == "officeorgrepmember"
               ^^^^^
/usr/local/bundle/gems/metanorma-ieee-1.0.0/lib/isodoc/ieee/html_convert.rb:58:in `affiliation_table1'
```
occurs in the metanorma-ieee, but looks like it's not critical, because the previous release (https://github.com/metanorma/metanorma-docker/actions/runs/3514967518/jobs/5896040140) created successfully with this error.

Could you run the release workflow manually, please?
The new release is important for https://github.com/metanorma/metanorma-ogc/issues/473.

**Comment by CAMOBAP** [comment]
https://github.com/metanorma/metanorma-docker/actions/runs/3736196218
