### ISSUE TITLE
Make docker compilation of samples run in strict mode

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-docker#172]
I have realised that the generation of Presentation XML has been aborting in docker runs, but that is not resulting in a crash out of the docker run, which means I do not find out about it.

To remedy this, I have implemented `metanorma compile -S true` in https://github.com/metanorma/metanorma/issues/270 , as a strict mode, to ensure that any raised errors in isodoc result in an abort.

To illustrate: the current released version of metanorma-iso, 2.3.2, crashes on generating Presentation XML for mn-samples-iso/sources/directives/part1-consolidated-iso , but metanorma compile keeps going (with an earlier available version), and the docker run keeps going too. With metanorma compile -S true, I'm hoping that particular document will crash, so I will know there is a problem.

Right now, https://github.com/metanorma/metanorma-cli/pull/293 and https://github.com/metanorma/metanorma/pull/271 , implementing strict compilation, are still a PR. Once strict compilation is working, I'm expecting to find a lot of issues in the samples directories that I did not realise are there. (So I will need warning from you about when you will get to this!)

**Comment by opoudjis** [comment]
Confirmed `bundle exec metanorma -S true document.adoc` crashes for the metanorma-iso version and file mentioned above.

**Comment by CAMOBAP** [comment]
@opoudjis should we have https://github.com/metanorma/metanorma-cli/pull/293/files#diff-e7dd9d05f2059a65355662901087f019920e0149ff220797800d3207052c4deaR39 to generate command too?

**Comment by ronaldtse** [comment]
> @opoudjis should we have https://github.com/metanorma/metanorma-cli/pull/293/files#diff-e7dd9d05f2059a65355662901087f019920e0149ff220797800d3207052c4deaR39 to `generate` command too?

Yes please, thanks @CAMOBAP !

**Comment by opoudjis** [comment]
We should. I've agreed to implement it and I have reopened https://github.com/metanorma/metanorma/issues/270 to do so. But I'm about to leave town for a week, and @CAMOBAP, if you get to it before I do, I will not complain...

**Comment by CAMOBAP** [comment]
Done, waiting for metanorma release

**Comment by opoudjis** [comment]
Metanorma release is happening Monday.
