### ISSUE TITLE
Replace outdated yuichielectric/dive-action@0.0.4

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-docker#177]
### Problem

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: yuichielectric/dive-action@0.0.4. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.Show more

### Proposed solution

Create our own composite action for dive command based on https://github.com/wagoodman/dive#installation

**Comment by ronaldtse** [comment]
Agree, unless there is another existing dive action that we can use.
