### ISSUE TITLE
[alpine] `ArgumentError: undefined class/module YAML::`

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-docker#178]
### Problem

https://github.com/metanorma/metanorma-docker/actions/runs/6091967095/job/16530985061#step:12:1608

### Possible solution

https://github.com/rubygems/rubygems/issues/6909#issuecomment-1692394837

**Comment by ronaldtse** [comment]
Alpine is not urgent. We don't need to fix this right now.

**Comment by CAMOBAP** [comment]
It's gone in last release
