### ISSUE TITLE
(URGENT) Metanorma docker container missing LaTeXML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#18]
This docker container must contain all the prerequisites of running metanorma. Right now it fails due to:

```
Error: No such file or directory - latexmlmath, 
```

@CAMOBAP795 can you please help fix this ASAP? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse it's very strange because we use https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh inside docker let me check

**Comment by CAMOBAP795** [comment]
Cannot reproduce it on my end, my steps:

```
docker pull metanorma/metanorma
docker run -v "$(pwd)":/metanorma/ metanorma/metanorma latexmlmath --help
```

@ronaldtse maybe I missed something?

**Comment by ronaldtse** [comment]
I see the same results, the metanorma docker container should work. Maybe it was on Windows...? Forgot...
