### ISSUE TITLE
1.10.1 images size increased

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-docker#188]
investigation...

**Comment by CAMOBAP** [comment]
apt-get install take almost twie more than previously

459MB in [1.10.0](https://github.com/metanorma/metanorma-docker/actions/runs/9363924644/job/25787592009#step:6:18)
vs
864MB in [1.10.1](https://github.com/metanorma/metanorma-docker/actions/runs/9564165352/job/26516333957#step:6:18)

To be updated

**Comment by CAMOBAP** [comment]
Extra size added by `xmi` gem

```
> docker run --rm metanorma/metanorma:1.10.1 du -sh /usr/local/bundle/gems/xmi-0.3.0
384M	/usr/local/bundle/gems/xmi-0.3.0
...
> docker run --rm metanorma/metanorma:1.10.0 du -sh /usr/local/bundle/gems/xmi-0.3.0
du: cannot access '/usr/local/bundle/gems/xmi-0.3.0': No such file or directory
```

Analyzed by `docker-diff` from `brew install moul/moul/docker-diff`

I'm not sure that we can do something about it so just closing this one

@ronaldtse FYI

**Comment by ronaldtse** [comment]
Oh no that size increase is crazy. The gem does not actually require this much space at all. It must be packaging things it shouldn't. 

Can you please file an issue at the XMI gem? Thanks. 

Ping @kwkwan please fix this ASAP. Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse @kwkwan this is all references i.e. /usr/local/bundle/gems/xmi-0.3.0/references

**Comment by CAMOBAP** [comment]
Reported https://github.com/lutaml/xmi/issues/30
