### ISSUE TITLE
latest version docker image throws errors

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-docker#25]
The following command threw an error

`docker run -v "$(pwd)":/metanorma/ -w /metanorma metanorma/metanorma "metanorma -t ogc -x xml,html,doc ./document.adoc"`

The error message is

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"metanorma -t ogc -x xml,html,doc ./document.adoc\": stat metanorma -t ogc -x xml,html,doc ./document.adoc: no such file or directory": unknown.`

However, the following command works

`docker run -v "$(pwd)":/metanorma/ -w /metanorma metanorma/metanorma:1.1.8 "metanorma -t ogc -x xml,html,doc ./document.adoc"`

**Comment by ronaldtse** [comment]
@ghobona this must have been caused by the latest docker container streamlining (ping @abunashir). 

Could you please try dropping the double quotes? Thanks!

**Comment by ghobona** [comment]
It works without the quotes. 

`docker run -v "$(pwd)":/metanorma/ -w /metanorma metanorma/metanorma metanorma -t ogc -x xml,html,doc ./document.adoc`

Thanks for the help.

**Comment by ronaldtse** [comment]
Thank you @ghobona for confirming! 

@abunashir could you help update the docker documentation on Metanorma.com ? (I know the docker hub docs have been updated)

**Comment by abunashir** [comment]
@ronaldtse done!
