### ISSUE TITLE
Synchronization of release with `metanorma-cli`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#26]
For every `metanorma-cli` release, we should build a new Metanorma docker container. How can we synchronize this?

**Comment by CAMOBAP795** [comment]
@ronaldtse probably we can modify a little bit travis ci config https://github.com/metanorma/metanorma-cli/blob/master/.travis.yml#L21-L37

Will be updated...

**Comment by CAMOBAP795** [comment]
@ronaldtse both:
 - https://github.com/metanorma/metanorma-docker/pull/29
 - https://github.com/metanorma/metanorma-cli/pull/111

are ready for review

**Comment by CAMOBAP795** [comment]
@ronaldtse should we make `mn` image on docker hub?

**Comment by ronaldtse** [comment]
@CAMOBAP795 yes, don't we already have it?

**Comment by CAMOBAP795** [comment]
AFAIK we have separation for images
 - `metanorma` for releases
 - `mn` for non-stable metanorma

As I see on docker hub we have only `metanorma` but haven't `mn`

**Comment by ronaldtse** [comment]
@CAMOBAP795 just created, you have access. Thanks!

**Comment by ronaldtse** [comment]
@CAMOBAP795 please close this when done. Thanks!
