### ISSUE TITLE
Provide list of packages/software included in Docker container

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#30]
For compliance (and informational) purposes, some users need a manifest of what packages/software is included in the Docker container.

This task is to provide this as documentation.

It is straightforward to provide a high level list as the first priority, such as:

* Puppeteer (with Google Chrome)
* PlantUML with the Java subsystem
* LaTeXML with Perl
* Metanorma with Ruby
* etc.

@abunashir could you help with this? Thanks!

**Comment by abunashir** [comment]
Sure, It also includes `node` and `npm`?
