### ISSUE TITLE
Post documentation on Docker Hub

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#31]
@abunashir can you help post the resulting documentation on Docker Hub? Thanks!

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-docker/pull/23#issuecomment-523735263_

**Comment by abunashir** [comment]
@ronaldtse Done here: https://hub.docker.com/r/metanorma/metanorma, Btw, docker documentation doesn't support asciidoc yet, should we consider changing the documentation here to markdown, so we can copy/paste in the future?

**Comment by ronaldtse** [comment]
@abunashir yeah sure, please go ahead. Thanks!

**Comment by abunashir** [comment]
@ronaldtse done in the attached PR, please let me know if there is anything else.
