### ISSUE TITLE
Upgrade image to Ruby 2.6

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#39]
The Debian running Ruby 2.5 is old. We should get it upgraded to avoid problems like #37 and #38 .

@CAMOBAP795 can you help with this? Thanks.

**Comment by CAMOBAP795** [comment]
- https://github.com/metanorma/mn-itu-docs/pull/5 - some bug in relaton

**Comment by CAMOBAP795** [comment]
@ronaldtse I need your help with reviewing related PRs

**Comment by ronaldtse** [comment]
@CAMOBAP795 could you help with https://github.com/metanorma/metanorma-docker/pull/40#issuecomment-532035265 ?

**Comment by ronaldtse** [comment]
Merged, closing.
