### ISSUE TITLE
Docker images not allowing build of PDFs due to missing `npm`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#42]
We have to fix this soon as PDF generation is now broken in Docker containers.

e.g. https://github.com/CalConnect/csd-transcription-systems/commit/ae74b1172fc991ef59e6cccf289faadf40c9714e/checks

```
/usr/local/bundle/gems/metanorma-0.3.15/lib/metanorma/output/pdf.rb:14:in ``': No such file or directory - npm (Errno::ENOENT)
1387
	from /usr/local/bundle/gems/metanorma-0.3.15/lib/metanorma/output/pdf.rb:14:in `convert'
1388
	from /usr/local/bundle/gems/isodoc-1.0.3/lib/isodoc/pdf_convert.rb:33:in `convert'
1389
	from /usr/local/bundle/gems/metanorma-csd-1.3.2/lib/metanorma/csd/processor.rb:36:in `output'
1390
```

**Comment by CAMOBAP795** [comment]
@ronaldtse fixed in https://github.com/metanorma/metanorma-docker/commit/18626eb1f90993d55fb2de47f6acc199d5d546c3

**Comment by ronaldtse** [comment]
@CAMOBAP795 is the new image built? Can you try in this repo which uses GitHub Actions via Docker? https://github.com/CalConnect/csd-admin-documents 

Thanks!

**Comment by CAMOBAP795** [comment]
Not fixed by 18626eb looking for another solution

**Comment by CAMOBAP795** [comment]
https://github.com/metanorma/metanorma-docker/commit/a3c66d493028d93316b0f411cb24e91cb06f152b - fixed

**Comment by CAMOBAP795** [comment]
npm not found fixed, but instability still exists "Navigation failed because browser has disconnected! (RuntimeError)"

**Comment by ronaldtse** [comment]
https://github.com/GoogleChrome/puppeteer/issues/4679

**Comment by ronaldtse** [comment]
Seems that it’s a common issue that can be fixed? https://stackoverflow.com/questions/54836746/puppeteer-fails-in-docker-container-browser-has-disconnected

**Comment by CAMOBAP795** [comment]
@ronaldtse I'm not sure that this is right fix because I didn't observe this problem locally (I use docker too) still ivestigating

**Comment by CAMOBAP795** [comment]
The issue have random nature, I have a feeling that https://github.com/GoogleChrome/puppeteer/issues/4911#issuecomment-534781138 will fix this

**Comment by ronaldtse** [comment]
Ping @CAMOBAP795 we've got a user complaining about this. Any updates?

**Comment by CAMOBAP795** [comment]
CalConnect magically fixed now

At this point, I have only one assumption - broken/buggy chrome binary

- When we install puppeteer, it downloads some version of chromium binary
- looks like https://hub.docker.com/layers/metanorma/metanorma/1.2.6/images/sha256-380af0412c87eafb64128e0b7b399179f1062379644ceff919d42329b1d9a529 contains a bad one
 - Nick did a release of metanorma-docker recently, this is why it doesn't happen anymore

This is still my assumption, but I will check it today

**Comment by CAMOBAP795** [comment]
According to last comment, not proven for OSX but maybe that a case for Linux.

I think we should not spent time on it right now
So I propose to close this one

@ronaldtse how do you think?
