### ISSUE TITLE
Docker image missing IETF compilation files

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#43]
@CAMOBAP795 can you help fix this? We just need to include xml2rfc inside the container. Thanks.

```sh
[metanorma-ietf] Error: unable to generate txt, the command `xml2rfc` is not found in path.
97
[metanorma-ietf] Error: unable to generate html, the command `xml2rfc` is not found in path.
```

**Comment by CAMOBAP795** [comment]
@ronaldtse yep, we definitely install `xml2rfc` but looks like it's not in `PATH`

**Comment by ronaldtse** [comment]
The particular issue occurs on https://github.com/CalConnect/csd-subscription-upgrade -- perhaps you can fork it and see how you can fix this?

**Comment by CAMOBAP795** [comment]
Merged waiting for publishing to try

**Comment by CAMOBAP795** [comment]
As I see the fix works

[csd-subscription-upgrade.txt](https://github.com/metanorma/metanorma-docker/files/3810898/csd-subscription-upgrade.txt)

**Comment by ronaldtse** [comment]
@CAMOBAP795 excellent!
