### ISSUE TITLE
Metanorma docker build failing

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-docker#46]
https://github.com/metanorma/metanorma-docker/commit/d304c08777b8f8febc04fb7b21d0600100b7a88d/checks?check_suite_id=372355060

**Comment by abunashir** [comment]
This is an ongoing issue with the latest bundler release and official ruby image, There are some fixes coming up soon. I've added a temporary fix by locking the bundler version to an earlier version, this should resolve the issue for now.

But, let's also keep a followup issue for the future to update it once we have an actual solution on the bundler/ruby image side.
