### ISSUE TITLE
Remove temporary fix for bundler

### ISSUE THREAD

**Issue by abunashir** [metanorma/metanorma-docker#48]
This is a followup for - https://github.com/metanorma/metanorma-docker/pull/47#issue-357509647, we don't necessarily need to work on this on until there are some official releases for bundler and ruby official image.

I'm keeping it open for reference and assigning it to myself.

**Comment by ronaldtse** [comment]
Thanks @abunashir for tracking!

**Comment by opoudjis** [comment]
@ronaldtse Should this issue be reactivated?

**Comment by ronaldtse** [comment]
@abunashir can we act on this now? Thanks.

**Comment by abunashir** [comment]
Indeed, I just checked with the latest version and seems to be working now. Created a PR 🚀
