### ISSUE TITLE
docker failing to install pip, so cannot update

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-docker#49]

**Comment by ronaldtse** [comment]
ping @CAMOBAP795

**Comment by ronaldtse** [comment]
This might be related to the deprecation of Python 2, might need to do this first:
```
sudo apt-get install -y python3-pip
```

**Comment by CAMOBAP795** [comment]
Looks like fixed by @ronaldtse already https://github.com/metanorma/metanorma-docker/commit/a9c7cb4c73dca0526fc7c1a9e85bd15e3e0ece20

**Comment by ronaldtse** [comment]
This is fixed in a9c7cb4

**Comment by opoudjis** [comment]
Issue has reemerged: https://github.com/metanorma/metanorma-docker/runs/417185859?check_suite_focus=true

**Comment by CAMOBAP795** [comment]
@opoudjis looks like you did tag on https://github.com/metanorma/metanorma-docker/commit/84c8a9fc72d4b889734f1a8d441d291cba0f0f9a some outdated commit, because if you will check Dockerfile.in for it, there is no `python-pip3` installation

I will retag it

**Comment by ronaldtse** [comment]
@CAMOBAP795 is this fixed now?

**Comment by CAMOBAP795** [comment]
@ronaldtse yes, in fact, this was fixed by you

For some reason, Github Actions didn't start on `git tag -f ...`, so I just pushed another tag

**Comment by CAMOBAP795** [comment]
I forgot that tag must correlate with metarnorma-cli, should be fixed now

**Comment by CAMOBAP795** [comment]
https://github.community/t5/GitHub-Actions/How-to-trigger-GitHub-Actions-on-retag

**Comment by opoudjis** [comment]
So Alex, what should I be doing differently?

````
<update metanorma-cli version number in> metanorma/metanorma-docker//Makefile 
git commit
git push
git tag <metanorma-cli version number>
git push --tags
````

**Comment by ronaldtse** [comment]
Closing this.
