### ISSUE TITLE
Add testing for all available samples repositories (mn-samples-*)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#59]
Add testing for all available samples repositories (mn-samples-*)

For @camobap795

_Originally posted by @CAMOBAP795 in https://github.com/metanorma/metanorma-docker/pull/58#issuecomment-589996244_

**Comment by CAMOBAP795** [comment]
@ronaldtse sorry for the confusion, you are always stepping ahead) https://github.com/metanorma/metanorma-docker/issues/56 was reported by you 14 days ago 

So I'm closing this one in favor of #56
