### ISSUE TITLE
Auto-build Docker container on GitLab

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#6]
We want to automatically build the "metanorma/metanorma" Docker container on pushes to this repo. (i.e. when the metanorma version changes)

@CAMOBAP795 can you help with this? Thanks!

**Comment by ronaldtse** [comment]
This repo is now mirrored at https://gitlab.com/ribose/metanorma-docker/ (you have access)

**Comment by CAMOBAP795** [comment]
@ronaldtse thanks, I confirm that I have access, as I see, we need to:
 - to setup CI (highly likely travis.ci) to build container
 - push to docker-hub if tag pushed to repo

Right?

**Comment by ronaldtse** [comment]
@camobap795 we probably have to use GitLab CI to build and push the container, I’m not aware that Travis can be used to build and push containers?

**Comment by CAMOBAP795** [comment]
@ronaldtse np, I'm ok to go with GitLab CI (I have used it before)

BTW Travis can be used for docker push https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry

**Comment by ronaldtse** [comment]
Either way works for us, but not sure if with Travis we can use the container definition specified.

**Comment by ronaldtse** [comment]
Any updates? Thanks!

**Comment by CAMOBAP795** [comment]
Almost done, could you please tell me docker user passwd for CI ?

**Comment by CAMOBAP795** [comment]
@ronaldtse I propose to close this one

**Comment by ronaldtse** [comment]
OK, thanks.
