### ISSUE TITLE
Tests for sample repos should always run all flavors and show errors at the end

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#66]
We want to have the build run for all flavors, i.e. so that the flavors don't block each other. Right now, all flavors are run in sequence but if one flavor fails the ones after won't run.

e.g. store the errors in a separate file for a run, and if there are errors, print out the log files at the end and then report the error.

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-docker/pull/65#issuecomment-599311729_

**Comment by CAMOBAP** [comment]
Currently, we have a reverse problem, it's don't stop on error, working to implement this logic

**Comment by CAMOBAP** [comment]
Done
