### ISSUE TITLE
Make metanorma-docker work with `metanorma setup` on separate volume

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#73]
We need to make a new volume inside the Docker container, e.g. /fonts to allow this:

```
docker run -v metanorma -it metanorma/metanorma setup
=> creates a volume mn-fonts that sets up fonts in the computer

docker run -v metanorma:~/.metanorma -it metanorma/metanorma setup
=> download fonts in VOL:/metanorma/fonts => ~/.metanorma/fonts
```

We need to have `VOLUME /metanorma` or something like this in the `Dockerfile`.

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-docker/pull/72#issuecomment-623973673_

**Comment by CAMOBAP** [comment]
Here is my update after research

> docker run -v metanorma -it metanorma/metanorma setup
> => creates a volume mn-fonts that sets up fonts in the computer

AFAIK There is no way to mount/create docker volume from the inside of the Docker

> docker run -v metanorma:~/.metanorma -it metanorma/metanorma setup
> => download fonts in VOL:/metanorma/fonts => ~/.metanorma/fonts

The command `docker run -v ~/.metanorma:/root/.metanorma -it metanorma/metanorma metanorma setup` will works out-of-box once https://github.com/metanorma/metanorma-cli/pull/139 will be merged

@ronaldtse if we need be able to configure fonts installation path this need to be implemented in metanorma-cli first, but I'm not sure that we need this

**Comment by CAMOBAP** [comment]
@ronaldtse got it but without modification in https://github.com/metanorma/metanorma-cli/pull/139 we cannot achieve this, https://github.com/metanorma/metanorma-cli/pull/139#issuecomment-626759731

**Comment by CAMOBAP** [comment]
@ronaldtse please confirm if this still an actual task.

As far as I see we can simply run `metanorma setup` from the container and don't need to `VOLUME /fonts`, correct me if I'm wrong

**Comment by ronaldtse** [comment]
@CAMOBAP by using the `VOLUME` command the user can override the local storage for fonts, allowing for caching locally across docker runs.

**Comment by CAMOBAP** [comment]
@ronaldtse this task doesn't look actual anymore after https://github.com/metanorma/metanorma-standoc/issues/375#issuecomment-728725926

**Comment by ronaldtse** [comment]
@CAMOBAP this task should be changed to allow the "font cache" (where the fonts used by Metanorma) are installed to, to be in a VOLUME.

**Comment by CAMOBAP** [comment]
Done already in the scope of #97
