### ISSUE TITLE
Impossible to install gems in container from Gemfile

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-docker#77]
### Intro

Recently I have fixed a couple of issues related to problems with installation gems from host Gemfile:
 - https://github.com/metanorma/mn-samples-mpfa/issues/20
 - https://github.com/metanorma/csa-caiq/issues/11

The fix by itself is in those lines: https://github.com/metanorma/mn-samples-mpfa/blob/master/.github/workflows/docker.yml#L41-L45

Long story short: in a docker container, only `bundler add` works for some reason, `bundle install` doesn't work

### Expected result

Simple `bundle install` should work for host's Gemfile

### Proposed solution

To be honest, IDK what causing of these problems, so I don't have a solution at this moment, I still feeling a lack of understanding the root of the issue, but this is something clearly related to bundler logic

Mode investigation details in attached tickets

**Comment by CAMOBAP** [comment]
@ronaldtse @abunashir please let me know if you have any idea about roots of the problem

**Comment by ronaldtse** [comment]
@ribose-jeffreylau was able to get around this issue with the combination of:

* git clone
* gem build
* sed /setup/Gemfile.lock

**Comment by CAMOBAP** [comment]
Thanks for the information, but `bundle add ...` in comparison with solution aboce looks much cleaner. I will develop this solution to support github gems

**Comment by CAMOBAP** [comment]
The script is ready https://github.com/metanorma/metanorma-build-scripts/blob/master/gemfile-to-bundle-add.sh
