### ISSUE TITLE
Auto-build Docker container on Travis

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#8]
Just like #6 we actually prefer building on Travis since we don't need to maintain a clone on GitLab.

Apparently Travis CI works for building docker images too:

* https://ops.tips/blog/travis-ci-push-docker-image/
* https://giorgos.sealabs.net/build-and-test-against-docker-images-in-travis.html

**Comment by CAMOBAP795** [comment]
@ronaldtse please:
 - enable travis for this repo
 - please tell me [encrypted value](https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml) of  `DOCKER_LOGIN_USERNAME`, `DOCKER_LOGIN_PASSWORD`

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you let me know your email used for docker hub?
