### ISSUE TITLE
metanorma/mn not showing latest commit with font fixed

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#84]
https://github.com/metanorma/metanorma-ogc/issues/145

This is despite the git ref here: https://github.com/metanorma/metanorma-docker/commit/ea518ee804220f5b57f5db4e87dd3f5629c5d4e8

@CAMOBAP can you help fix this?

**Comment by CAMOBAP** [comment]
@ronaldtse on regular pushes to master we are update `latest` tags only:
 - https://hub.docker.com/layers/metanorma/mn/latest/images/sha256-fa1045c3add2125912623525521ea76ba4d26ef0c9c53db710d0ce27c648bbe0?context=explore
 - https://hub.docker.com/layers/metanorma/mn-ubuntu/latest/images/sha256-f8c7c6ca7d3e4a4cd631da5b93815afc0dfaf4370c9f451be10c8f40afbcd698?context=explore

for 1.2.12 it stays 'old' one

**Comment by ronaldtse** [comment]
I see, however, I'm getting the same result for both "latest" and "1.2.12"... i.e. the fonts were not fixed.

**Comment by ronaldtse** [comment]
Locally, if I run git head, it is fixed.

**Comment by CAMOBAP** [comment]
Should ve fixed now

**Comment by ronaldtse** [comment]
Confirmed!
