### ISSUE TITLE
feature/pres_xml docker

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-docker#87]
As discussed: the implementation of PDF XSLT is impacted by ongoing changes in the postprocessing of XML, which is initiated under https://github.com/metanorma/metanorma-standoc/issues/285. I will be updating the entire metanorma stack against the branch feature/pres_xml. 

We need a version of metanorma-docker to trigger branch-specific builds of the samples repositories: Every time some trigger happens that you will determine (maybe a commit in the feature/pres_xml branch of metanorma-cli, which doesn't exist yet?),  metanorma-docker is compiled against the feature/pres_xml branch of the entire metanorma stack (not html2doc); and we used that feature/pres_xml branch of metanorma-docker to compile XML documents in all metanorma samples repositories, in the feature/pres_xml branch for those repositories.

Needs to be done in time for @Intelligent2013 to be able to work on its output; should be 1-2 weeks.

**Comment by opoudjis** [comment]
I've already moved the code to pres_xml1. Am I going to need to move it back to pres_xml?

**Comment by CAMOBAP** [comment]
@opoudjis thanks for the detailed explanation, could you please clarify some moments:
 1. Will we release `feature/pres_xml` gems to rubygems.org, or only keep them in git?
 2. I propose to keep `feature/pres_xml` branch for `metanorma-docker` too for consistency, is that ok?
 3. Which repos except metanorma-cli should be able to trigger a new build for docker image? 
 4. Any suggestion for a name for new docker image? How about `mn/mn:feature_pres_xml`

**Comment by opoudjis** [comment]
From your questions, clearly I need to migrate pres_xml1 back to pres_xml

1. This is still a development branch (it's for Alex Dyuzhev to update his XSLTs against prior to release, as the migration of functionality involved is incremental). So the gems involved will have their production, master branches released to rubygems; the pres_xml branch needs to be confined to docker
2. Sure
3. Hm. I think metanorma-cli is enough. I will need to be able to do a manual trigger against what's currently on github; but that's just restarting the GitHub actions job
4. That's fine.

**Comment by CAMOBAP** [comment]
@opoudjis thanks for answers, as I see https://github.com/metanorma/metanorma-cli/tree/feature/pres_xml already exists so I think I can proceed at least with PR

**Comment by CAMOBAP** [comment]
@opoudjis @Intelligent2013 one more question should we trigger templates/samples repository for this new docker image?

**Comment by CAMOBAP** [comment]
Ready for review:
 - https://github.com/metanorma/metanorma-cli/pull/160
 - https://github.com/metanorma/metanorma-docker/tree/feature/pres_xml

**Comment by opoudjis** [comment]
Sorry! I think I'm happy to trigger the job manually. The updates to the branch may be cumulative, but I will have a notion of finishing updates in a feature before handing over to @Intelligent2013.

**Comment by CAMOBAP** [comment]
one more change needs to be done
 - implement `feature/pres_xml` branches on mn-samples which will upload `presentation.xml` as artifact

**Comment by CAMOBAP** [comment]
@me One more point to double-check https://github.community/t/how-to-trigger-repository-dispatch-event-for-non-default-branch/14470

**Comment by CAMOBAP** [comment]
> one more change needs to be done
> - implement feature/pres_xml branches on mn-samples which will upload presentation.xml as artifact

implemented on the master branch to run on up to date documents

**Comment by opoudjis** [comment]
OK, I missed this change when I did my newest pres_xml branch update, but this means that when I manually trigger the pres_xml job on metanorma-cli, Presentation XML output will be generated?

**Comment by ronaldtse** [comment]
@opoudjis is this ticket still in progress? Why do we need a separate branch for presentation XML?

**Comment by opoudjis** [comment]
As discussed for future testing of PDF generation using presentation XML updates not yet to be released to general code. But in practice, we haven't bothered, and we have permitted the HTML and PDF not to be in sync.

**Comment by CAMOBAP** [comment]
Hmmm, I have doublechecked and `docker-pres_xml.yml` https://github.com/metanorma/mn-samples-cc/actions/workflows/docker-pres_xml.yml and looks like something doesn't work because it was never triggered

@opoudjis @ronaldtse could you please confirm that this task is still actual?

**Comment by ronaldtse** [comment]
@opoudjis what issue do we still have here?

**Comment by opoudjis** [comment]
The workflow that the separate branch for presXML proposed to used in Docker never happened, as I said in Oct 2020. This issue is no longer current, closing.
