### ISSUE TITLE
On every metanorma-docker release, re-deploy mn-samples-* repos using the latest released docker container

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-docker#90]
Currently, when the docker-mn.yml workflow is triggered, the samples directories are tested.

However, they need to be compiled to gh-pages, not just tested: the changes in rendering with each release, for each samples directory, need to be visible externally.

Right now, because I was assuming this was already happening, I am not manually triggering samples compilation. And it is not practical for me to do so: docker takes a half hour to compile, and I usually go to bed right after finishing release.

**Comment by opoudjis** [comment]
@ronaldtse Please confirm this is needed

**Comment by ronaldtse** [comment]
They are already automatically done. e.g. ITU http://metanorma.github.io/mn-samples-itu

**Comment by ronaldtse** [comment]
Specifically in mn-samples-itu , it is this line that deploys it:
https://github.com/metanorma/mn-samples-itu/blob/399ae4abe680aaea9e9d84df5cf73816fd5e1077/.github/workflows/docker.yml#L53

Closing now.

**Comment by CAMOBAP** [comment]
I think @opoudjis means that make sense to trigger gh-pages deploy on release too.

Currently we as part of metanorma-docker flow we do testing by cloning samples repositories and run build with docker. With this approach gh-pages stays untouched, because we doing this 'locally'

It sounds reasonable to me to trigger samples repos once new docker image pushed to docker hub

@ronaldtse how do you think?

**Comment by ronaldtse** [comment]
I misunderstood what @opoudjis meant (well, it was poorly described).

I agree with @CAMOBAP that once the released docker image is pushed to docker hub, we can trigger a re-deploy for all mn-sample-* repos.

@CAMOBAP I also want to be sure that a test release of metanorma-docker will not trigger the mn-samples-* repos (the last thing we want is to have those deployed repos break!)

**Comment by CAMOBAP** [comment]
@ronaldtse to be on the same page by "test release of metanorma-docker" you mean `metanorma/mn` updates right?

**Comment by ronaldtse** [comment]
@CAMOBAP correct, I was unclear there.

**Comment by CAMOBAP** [comment]
@ronaldtse @opoudjis https://github.com/metanorma/metanorma-docker/pull/91 - done

I was wrong, previously we had this logic https://github.com/metanorma/metanorma-docker/blob/master/.github/workflows/docker-mn.yml#L36-L4 

But it triggered build for any push to master, now I have restricted it to release only

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Comment by CAMOBAP** [comment]
Done
