### ISSUE TITLE
(URGENT) metanorma-docker versions not tagged according to metanorma-cli

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#92]
1.3.7.3 is created in metanorma-cli, but metanorma-docker is only at v1.3.7.1???

This urgently needs fixing.

<img width="846" alt="Screen Shot 2020-09-12 at 9 43 59 AM" src="https://user-images.githubusercontent.com/11865/92984411-7d46dd00-f4dc-11ea-8b9b-995e8842e40d.png">

**Comment by CAMOBAP** [comment]
<img width="860" alt="Screen Shot 2020-09-12 at 7 46 13 AM" src="https://user-images.githubusercontent.com/2169738/92987543-0ace0100-f4cc-11ea-8b52-30ceb5d26779.png">

https://hub.docker.com/r/metanorma/metanorma/tags - also updated

@ronaldtse looks right, isn't it?

**Comment by ronaldtse** [comment]
Yes, looks right. Thanks @CAMOBAP !

**Comment by ronaldtse** [comment]
However @CAMOBAP was the 1.3.7.2 tag not run because of failure? I had to manually tag v1.3.7.3 in metanorma-cli.

**Comment by CAMOBAP** [comment]
> However @CAMOBAP was the 1.3.7.2 tag not run because of failure?

@ronaldtse I can confirm this. 

Let me prepare a summary on this situation how we can improve this, I will post it in https://github.com/metanorma/metanorma-cli/issues/174 because the topic perfectly fit the problem

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !
