### ISSUE TITLE
Unroll the flavors to multiple jobs (each in a separate container) to speed up GHA run

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#93]
https://github.com/metanorma/metanorma-docker/blob/e5dd3597091ca95211f88b8bb38ef6b240939eb6/Makefile#L121-L125

**Comment by CAMOBAP** [comment]
We need to find a way how we can share docker imaged between jobs https://github.community/t/whats-the-recommended-way-to-pass-a-docker-image-to-the-next-job-in-a-workflow/17225/11

Research in progress...

**Comment by ronaldtse** [comment]
@CAMOBAP isn't GHA's matrix functionality perfect for this? Then we can separate failures by the flavor as well.

**Comment by ronaldtse** [comment]
This workflow is a perfect example on how we can build the image, upload as artifact (with minimal `retention-days`), then run tests on the containers, before releasing them.

https://github.com/docker/build-push-action/blob/master/docs/advanced/share-image-jobs.md

**Comment by ronaldtse** [comment]
And this is building multiple platforms at the same time:
https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
