### ISSUE TITLE
Error processing tar file when pulling new docker image

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-docker#95]
When I run `docker pull metanorma/mn:latest`, I get this error:

```
latest: Pulling from metanorma/mn
bb79b6b2107f: Already exists 
e8b853ec9f22: Already exists 
d21147059b99: Already exists 
12beaa8b1a46: Already exists 
7d6e773ea12e: Already exists 
b9bec9af3907: Extracting  827.9MB/827.9MB
failed to register layer: Error processing tar file(exit status 1): write /usr/lib/jvm/java-11-openjdk-amd64/lib/server/classes.jsa: no space left on device
```

I have 96 GB available on my laptop. Does the new metanorma docker image really require more than 96 GB?

**Comment by ghobona** [comment]
The problem was docker and has been solved with a `docker system prune`

https://docs.docker.com/engine/reference/commandline/system_prune/

**Comment by ronaldtse** [comment]
Thanks @ghobona !
