### ISSUE TITLE
404 in ReadMe target URL

### ISSUE THREAD

**Issue by odeclas** [metanorma/metanorma-docker#98]
The alternative install instructions lead to a 404 page on the metanorma site for this page - https://www.metanorma.org/author/topics/install/

**Comment by CAMOBAP** [comment]
@odeclas looks like you opened this link from 

<img width="864" alt="Screen Shot 2021-04-27 at 2 13 12 PM" src="https://user-images.githubusercontent.com/2169738/116232511-e543ee00-a762-11eb-9485-09fb756b7eb3.png">

This is an outdated menu, and we will remove it

cc @ronaldtse

**Comment by ronaldtse** [comment]
@odeclas @CAMOBAP thank you!

**Comment by CAMOBAP** [comment]
Done
