### ISSUE TITLE
fontist - Aborting without proper fonts installed

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-docker#99]
The latest version of the docker image now requires fonts to be downloaded each time.

When I execute `docker run`, it outputs the font license and then prints "[fontist] Aborting without proper fonts installed, make sure that you have set option --agree-to-terms"

So I then have to execute:

`docker run -v "$(pwd)":/metanorma metanorma/mn  metanorma compile --agree-to-terms -t ogc -x xml,html,doc document.adoc`

This means that it downloads the fonts each time `docker run` is executed, which adds about a minute to the build time.

**Comment by ghobona** [comment]
This issue happened when executing the following command:

`docker run -v "$(pwd)":/metanorma metanorma/mn  metanorma new -d best-practice -t ogc  -l https://github.com/metanorma/mn-templates-ogc MyBestPractice`

However the issue **did not** happen when executing the following command:

`docker run -v "$(pwd)":/metanorma metanorma/mn  metanorma new -d standard -t ogc  -l https://github.com/metanorma/mn-templates-ogc MyStandard`

**Comment by ronaldtse** [comment]
@ghobona there is a way to cache the fonts using the Docker image:

```
$ docker run -v "$(pwd)":/metanorma/ \
  -v ${HOME}/.fontist/fonts/:/config/fonts \
  -w /metanorma metanorma/metanorma \
  metanorma compile -t iso -x xml --agree-to-terms test.adoc
```

> This issue happened when executing the following command:
> However the issue did not happen when executing the following command:

I'm not sure why this occurs, because both document types should be using the same fonts. Let me file a bug.

**Comment by CAMOBAP** [comment]
> When I execute docker run, it outputs the font license and then prints 
> `"[fontist] Aborting without proper fonts installed, make sure that you have set option --agree-to-terms"`

@ronaldtse @ghobona this is expected behavior if `--agree-to-terms` missing

@ronaldtse is right to cache font please use the command from the https://github.com/metanorma/metanorma-docker/issues/99#issuecomment-829274013

**Comment by ghobona** [comment]
@CAMOBAP @ronaldtse Ok, thanks for the response.

**Comment by ronaldtse** [comment]
Thanks @ghobona !
